
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('ingredients').del()
    .then(function () {
      // Inserts seed entries
      return knex('ingredients').insert([
        {id: 1, name: 'asparagus'},
        {id: 2, name: 'broccoli'},
        {id: 3, name: 'carrot'},
        {id: 4, name: 'celery'},
        {id: 5, name: 'corn'},
        {id: 6, name: 'cucumber'},
        {id: 7, name: 'lettuce'},
        {id: 8, name: 'cabbage'},
        {id: 9, name: 'mushroom'},
        {id: 10, name: 'onion'},
        {id: 11, name: 'potato'},
        {id: 12, name: 'sweet potato'},
        {id: 13, name: 'squash'},
        {id: 14, name: 'zucchini'},
        {id: 15, name: 'tomato'},
        {id: 16, name: 'apple'},
        {id: 17, name: 'avocado'},
        {id: 18, name: 'banana'},
        {id: 19, name: 'blueberries'},
        {id: 20, name: 'cherries'},
        {id: 21, name: 'watermelon'},
        {id: 22, name: 'grapes'},
        {id: 23, name: 'nectarines'},
        {id: 24, name: 'lemon'},
        {id: 25, name: 'lime'},
        {id: 26, name: 'peaches'},
        {id: 27, name: 'orange'},
        {id: 28, name: 'pear'},
        {id: 29, name: 'plum'},
        {id: 30, name: 'cheese'},
        {id: 31, name: 'milk'},
        {id: 32, name: 'sour cream'},
        {id: 33, name: 'salsa'},
        {id: 34, name: 'yogurt'},
        {id: 35, name: 'cheddar'},
        {id: 36, name: 'cottage cheese'},
        {id: 37, name: 'swiss cheese'},
        {id: 38, name: 'parmesan cheese'},
        {id: 39, name: 'provolone cheese'},
        {id: 40, name: 'ricotta cheese'},
        {id: 41, name: 'goat cheese'},
        {id: 42, name: 'hot dog'},
        {id: 43, name: 'spam'},
        {id: 44, name: 'lunchmeat'},
        {id: 45, name: 'pork'},
        {id: 46, name: 'pork shoulder'},
        {id: 47, name: 'pork butt'},
        {id: 48, name: 'pork ribs'},
        {id: 49, name: 'bagel'},
        {id: 50, name: 'bread'},
        {id: 51, name: 'pita bread'},
        {id: 52, name: 'eggs'},
        {id: 53, name: 'olives'},
        {id: 54, name: 'basil'},
        {id: 55, name: 'cilantro'},
        {id: 56, name: 'ginger'},
        {id: 57, name: 'garlic'},
        {id: 58, name: 'oregano'},
        {id: 59, name: 'mint'},
        {id: 60, name: 'cinnamon'},
        {id: 61, name: 'sugar'},
        {id: 62, name: 'paprika'},
        {id: 63, name: 'parsley'},
        {id: 64, name: 'vanilla extract'},
        {id: 65, name: 'catfish'},
        {id: 66, name: 'crab'},
        {id: 67, name: 'lobster'},
        {id: 68, name: 'mussels'},
        {id: 69, name: 'oysters'},
        {id: 70, name: 'clams'},
        {id: 71, name: 'salmon'},
        {id: 72, name: 'shrimp'},
        {id: 73, name: 'tuna'},
        {id: 74, name: 'tilapia'},
        {id: 75, name: 'ahi'},
        {id: 76, name: 'red wine'},
        {id: 77, name: 'white wine'},
        {id: 78, name: 'olive oil'},
        {id: 79, name: 'canola oil'},
        {id: 80, name: 'steak'},
        {id: 81, name: 'tofu'},
        {id: 82, name: 'beef'},
        {id: 83, name: 'ground beef'},
        {id: 84, name: 'soy beans'},
        {id: 85, name: 'edamame'},
        {id: 86, name: 'garbanzo beans'},
        {id: 87, name: 'chickpeas'},
        {id: 88, name: 'oatmeal'},
        {id: 89, name: 'flour'},
        {id: 90, name: 'rice'},
        {id: 91, name: 'whipped cream'},
        {id: 92, name: 'almonds'},
        {id: 93, name: 'peanuts'},
        {id: 94, name: 'cashews'},
        {id: 95, name: 'crackers'},
        {id: 96, name: 'saltines'},
        {id: 97, name: 'sardines'},
        {id: 98, name: 'trout'},
        {id: 99, name: 'mackeral'},
        {id: 100, name: 'beef ribs'},
        {id: 101, name: 'octopus'},
        {id: 102, name: 'goat'},
        {id: 103, name: 'lamb'},
        {id: 104, name: 'duck'},
        {id: 105, name: 'prawns'},
        {id: 106, name: 'chestnuts'},
        {id: 107, name: 'water chestnuts'},
        {id: 108, name: 'watercress'},
        {id: 109, name: 'arugula'},
        {id: 110, name: 'beets'},
        {id: 111, name: 'romaine lettuce'},
        {id: 112, name: 'mesclun'},
        {id: 113, name: 'green beans'},
        {id: 114, name: 'snap peas'},
        {id: 115, name: 'coconut'},
        {id: 116, name: 'pine nuts'},
        {id: 117, name: 'curry'},
        {id: 118, name: 'yams'},
        {id: 119, name: 'sesame seeds'},
        {id: 120, name: 'bean sprouts'},
        {id: 121, name: 'radishes'},
        {id: 122, name: 'bok choy'},
        {id: 123, name: 'choy sum'},
        {id: 124, name: 'kidney beans'},
        {id: 125, name: 'black beans'},
        {id: 126, name: 'pinto beans'},
        {id: 127, name: 'refried beans'},
        {id: 128, name: 'thyme'},
        {id: 129, name: 'green onion'},
        {id: 130, name: 'pasta'},
        {id: 131, name: 'spaghetti'},
        {id: 132, name: 'fusilli'},
        {id: 133, name: 'ravioli'},
        {id: 134, name: 'linguine'},
        {id: 135, name: 'peanut butter'},
        {id: 136, name: 'almond butter'},
        {id: 137, name: 'nutella'},
        {id: 138, name: 'cranberry sauce'},
        {id: 139, name: 'cranberries'},
        {id: 140, name: 'jalapenos'},
        {id: 141, name: 'habanero'},
        {id: 142, name: 'cream cheese'},
        {id: 143, name: 'serrano'},
        {id: 144, name: 'bell peppers'},
        {id: 145, name: 'raspberries'},
        {id: 146, name: 'chocolate'},
        {id: 147, name: 'tomato sauce'},
        {id: 148, name: 'ketchup'},
        {id: 149, name: 'mayonnaise'},
        {id: 150, name: 'mustard'},
        {id: 151, name: 'relish'},
        {id: 152, name: 'hot sauce'},
        {id: 153, name: 'cantaloupe'},
        {id: 155, name: 'honeydew melon'},
        {id: 156, name: 'butternut squash'},
        {id: 157, name: 'rice cake'},
        {id: 158, name: 'apricots'},
        {id: 159, name: 'bitter melon'},
        {id: 160, name: 'cauliflower'},
        {id: 161, name: 'eggplant'},
        {id: 162, name: 'venison'},
        {id: 163, name: 'sriracha'},
        {id: 164, name: 'soy sauce'},
        {id: 165, name: 'sundried tomatoes'},
        {id: 166, name: 'tortillas'},
        {id: 167, name: 'salt'},
        {id: 168, name: 'pepper'},
        {id: 169, name: 'sauerkraut'},
        {id: 170, name: 'beef brisket'},
        {id: 171, name: 'cacao nibs'},
        {id: 172, name: 'honey'},
        {id: 173, name: 'seaweed'},
        {id: 174, name: 'kim chee'},
        {id: 175, name: 'bratwurst'},
        {id: 176, name: 'pickles'},
        {id: 177, name: 'agave syrup'},
        {id: 178, name: 'maple syrup'},
        {id: 179, name: 'cayenne pepper'},
        {id: 180, name: 'spirulina'},
        {id: 181, name: 'macadamia nuts'},
        {id: 182, name: 'snapper'},
        {id: 183, name: 'okra'},
        {id: 184, name: 'steel cut oats'},
        {id: 185, name: 'pineapple'},
        {id: 186, name: 'mango'},
        {id: 187, name: 'spinach'},
        {id: 188, name: 'banana peppers'},
        {id: 189, name: 'bread crumbs'},
        {id: 190, name: 'chives'},
        {id: 191, name: 'dill'},
        {id: 192, name: 'sea bass'},
        {id: 193, name: 'cod'},
        {id: 194, name: 'tahini'},
        {id: 195, name: 'squid'},
        {id: 196, name: 'calamari'},
        {id: 197, name: 'mozzarella cheese'},
        {id: 198, name: 'salami'},
        {id: 199, name: 'butter'},
        {id: 200, name: 'margarine'},
        {id: 201, name: 'jelly'},
        {id: 202, name: 'ham'},
        {id: 203, name: 'canned tuna'},
        {id: 204, name: 'lentils'},
        {id: 205, name: 'guava'},
        {id: 206, name: 'ramen'},
        {id: 207, name: 'udon'},
        {id: 208, name: 'beer'},
        {id: 209, name: 'jello'},
        {id: 210, name: 'papaya'}
      ]);
    });
};
