
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('ingredients').del()
    .then(function () {
      // Inserts seed entries
      return knex('ingredients').insert([
        {name: 'asparagus'},
        {name: 'broccoli'},
        {name: 'carrot'},
        {name: 'celery'},
        {name: 'corn'},
        {name: 'cucumber'},
        {name: 'lettuce'},
        {name: 'cabbage'},
        {name: 'mushroom'},
        {name: 'onion'},
        {name: 'potato'},
        {name: 'sweet potato'},
        {name: 'squash'},
        {name: 'zucchini'},
        {name: 'tomato'},
        {name: 'apple'},
        {name: 'avocado'},
        {name: 'banana'},
        {name: 'blueberries'},
        {name: 'cherries'},
        {name: 'watermelon'},
        {name: 'grapes'},
        {name: 'nectarines'},
        {name: 'lemon'},
        {name: 'lime'},
        {name: 'peaches'},
        {name: 'orange'},
        {name: 'pear'},
        {name: 'plum'},
        {name: 'cheese'},
        {name: 'milk'},
        {name: 'sour cream'},
        {name: 'salsa'},
        {name: 'yogurt'},
        {name: 'cheddar'},
        {name: 'cottage cheese'},
        {name: 'swiss cheese'},
        {name: 'parmesan cheese'},
        {name: 'provolone cheese'},
        {name: 'ricotta cheese'},
        {name: 'goat cheese'},
        {name: 'hot dog'},
        {name: 'spam'},
        {name: 'lunchmeat'},
        {name: 'pork'},
        {name: 'pork shoulder'},
        {name: 'pork butt'},
        {name: 'pork ribs'},
        {name: 'bagel'},
        {name: 'bread'},
        {name: 'pita bread'},
        {name: 'eggs'},
        {name: 'olives'},
        {name: 'basil'},
        {name: 'cilantro'},
        {name: 'ginger'},
        {name: 'garlic'},
        {name: 'oregano'},
        {name: 'mint'},
        {name: 'cinnamon'},
        {name: 'sugar'},
        {name: 'paprika'},
        {name: 'parsley'},
        {name: 'vanilla extract'},
        {name: 'catfish'},
        {name: 'crab'},
        {name: 'lobster'},
        {name: 'mussels'},
        {name: 'oysters'},
        {name: 'clams'},
        {name: 'salmon'},
        {name: 'shrimp'},
        {name: 'tuna'},
        {name: 'tilapia'},
        {name: 'ahi'},
        {name: 'red wine'},
        {name: 'white wine'},
        {name: 'olive oil'},
        {name: 'canola oil'},
        {name: 'steak'},
        {name: 'tofu'},
        {name: 'beef'},
        {name: 'ground beef'},
        {name: 'soy beans'},
        {name: 'edamame'},
        {name: 'garbanzo beans'},
        {name: 'chickpeas'},
        {name: 'oatmeal'},
        {name: 'flour'},
        {name: 'rice'},
        {name: 'whipped cream'},
        {name: 'almonds'},
        {name: 'peanuts'},
        {name: 'cashews'},
        {name: 'crackers'},
        {name: 'saltines'},
        {name: 'sardines'},
        {name: 'trout'},
        {name: 'mackeral'},
        { name: 'beef ribs'},
        { name: 'octopus'},
        { name: 'goat'},
        { name: 'lamb'},
        { name: 'duck'},
        { name: 'prawns'},
        { name: 'chestnuts'},
        { name: 'water chestnuts'},
        { name: 'watercress'},
        { name: 'arugula'},
        { name: 'beets'},
        { name: 'romaine lettuce'},
        { name: 'mesclun'},
        { name: 'green beans'},
        { name: 'snap peas'},
        { name: 'coconut'},
        { name: 'pine nuts'},
        { name: 'curry'},
        { name: 'yams'},
        { name: 'sesame seeds'},
        { name: 'bean sprouts'},
        { name: 'radishes'},
        { name: 'bok choy'},
        { name: 'choy sum'},
        { name: 'kidney beans'},
        { name: 'black beans'},
        { name: 'pinto beans'},
        { name: 'refried beans'},
        { name: 'thyme'},
        { name: 'green onion'},
        { name: 'pasta'},
        { name: 'spaghetti'},
        { name: 'fusilli'},
        { name: 'ravioli'},
        { name: 'linguine'},
        { name: 'peanut butter'},
        { name: 'almond butter'},
        { name: 'nutella'},
        { name: 'cranberry sauce'},
        { name: 'cranberries'},
        { name: 'jalapenos'},
        { name: 'habanero'},
        { name: 'cream cheese'},
        { name: 'serrano'},
        { name: 'bell peppers'},
        { name: 'raspberries'},
        { name: 'chocolate'},
        { name: 'tomato sauce'},
        { name: 'ketchup'},
        { name: 'mayonnaise'},
        { name: 'mustard'},
        { name: 'relish'},
        { name: 'hot sauce'},
        { name: 'cantaloupe'},
        { name: 'honeydew melon'},
        { name: 'butternut squash'},
        { name: 'rice cake'},
        { name: 'apricots'},
        { name: 'bitter melon'},
        { name: 'cauliflower'},
        { name: 'eggplant'},
        { name: 'venison'},
        { name: 'sriracha'},
        { name: 'soy sauce'},
        { name: 'sundried tomatoes'},
        { name: 'tortillas'},
        { name: 'salt'},
        { name: 'pepper'},
        { name: 'sauerkraut'},
        { name: 'beef brisket'},
        { name: 'cacao nibs'},
        { name: 'honey'},
        { name: 'seaweed'},
        { name: 'kim chee'},
        { name: 'bratwurst'},
        { name: 'pickles'},
        { name: 'agave syrup'},
        { name: 'maple syrup'},
        { name: 'cayenne pepper'},
        { name: 'spirulina'},
        { name: 'macadamia nuts'},
        { name: 'snapper'},
        { name: 'okra'},
        { name: 'steel cut oats'},
        { name: 'pineapple'},
        { name: 'mango'},
        { name: 'spinach'},
        { name: 'banana peppers'},
        { name: 'bread crumbs'},
        { name: 'chives'},
        { name: 'dill'},
        { name: 'sea bass'},
        { name: 'cod'},
        { name: 'tahini'},
        { name: 'squid'},
        { name: 'calamari'},
        { name: 'mozzarella cheese'},
        { name: 'salami'},
        { name: 'butter'},
        { name: 'margarine'},
        { name: 'jelly'},
        { name: 'ham'},
        { name: 'canned tuna'},
        { name: 'lentils'},
        { name: 'guava'},
        { name: 'ramen'},
        { name: 'udon'},
        { name: 'beer'},
        { name: 'jello'},
        { name: 'papaya'}
      ]);
    });
};
